#!/usr/bin/env python3
"""Generate the app's identifier crosswalk from the verification cache.

The corroboration badge has to count PAPERS, not identifiers. PMC6421268 and
PMID 30915065 are the same 2019 SCFA review; an entry citing both is
single-sourced, and 57 entries in this dataset do exactly that. Without this
map the badge would call every one of them corroborated.

Only pairs that actually co-occur in the data are emitted, so the file stays
small.

    python3 scripts/check_citation_coverage.py --verify   # refresh the cache
    python3 scripts/export_id_crosswalk.py                # regenerate the map
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from check_citation_coverage import canonical_map, load_claims  # noqa: E402

OUT = os.path.join("Porting to native react", "app", "src", "lib", "idCrosswalk.js")
HEADER = """// GENERATED by scripts/export_id_crosswalk.py - do not edit by hand.
//
// Maps every alternative identifier of a paper onto one canonical id, so the
// corroboration badge counts papers instead of identifiers. PMC6421268 and
// PMID 30915065 are one review, not two sources.
export const ID_CROSSWALK = """


def main():
    cache_path = sys.argv[1] if len(sys.argv) > 1 else ".citation_cache.json"
    try:
        cache = json.load(open(cache_path, encoding="utf-8"))
    except (OSError, ValueError):
        print(f"No cache at {cache_path}. Run --verify first.", file=sys.stderr)
        sys.exit(1)

    claims, _ = load_claims("seed_data.json", "symptom_data.json")
    used = set()
    for claim in claims:
        used |= claim.ids

    canon = canonical_map(cache)
    mapping = {i: c for i, c in canon.items() if i != c and i in used}

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER + json.dumps(mapping, indent=2, sort_keys=True) + "\n")
    print(f"{OUT}: {len(mapping)} alias -> canonical pairs "
          f"(from {len(used)} identifiers in use)")


if __name__ == "__main__":
    main()
