#!/usr/bin/env python3
"""
Regenerate gut-flora-atlas.readable.html — a read-only, human-formatted mirror
of gut-flora-atlas.html for browsing/grepping the code.

Why this exists: gut-flora-atlas.html's <script> is a single-line minified
React bundle (esbuild output) plus a hand-appended GFA_-prefixed plain-JS
section, all one giant line, painful to read directly. This script beautifies
just the JS and re-wraps it in the same HTML shell.

Requires the pure-Python `jsbeautifier` package (no Node needed — none is
installed in this project's dev environment). Install into a venv if it's
not already available:
    python3 -m venv .venv-readable && .venv-readable/bin/pip install jsbeautifier
    .venv-readable/bin/python3 scripts/make_readable.py

Do NOT edit gut-flora-atlas.readable.html directly — it is not wired into
the app's editing workflow. Edit gut-flora-atlas.html (see the workflow
described in NEED_TO_IMPLEMENT.md / ARCHITECTURE.md — exact-substring
python str.replace against the minified anchors), then re-run this script.

Verification this script's output preserves content exactly (done once when
this script was written, worth re-running spot-checks after any jsbeautifier
version bump): the two big embedded JSON-ish data blobs — the `qf()`
conditions array and `GFA_SYMPTOM_DATA_SHIPPED` — round-trip through
`json.loads()` on the BEAUTIFIED output and compare equal to seed_data.json /
symptom_data.json. See the git history around the commit that added this
file for the one-off verification script that also confirmed raw token
counts (function/GFA_/useState/useEffect/useMemo/var/let) match between the
original minified JS and the beautified JS, once you account for the
minifier's `let[`/`var[` (no-space-before-bracket) shorthand that the
beautifier correctly expands to `let [`/`var [`.
"""
import json
import sys

try:
    import jsbeautifier
except ImportError:
    sys.exit(
        "jsbeautifier not installed. Run:\n"
        "  python3 -m venv .venv-readable && .venv-readable/bin/pip install jsbeautifier\n"
        "  .venv-readable/bin/python3 scripts/make_readable.py"
    )

SRC = "gut-flora-atlas.html"
OUT = "gut-flora-atlas.readable.html"

HEADER_COMMENT = (
    "<!--\n"
    "  READ-ONLY, human-formatted mirror of gut-flora-atlas.html for browsing/grepping.\n"
    "  Generated by beautifying the exact same minified <script> content with jsbeautifier\n"
    "  (Python, no Node available in this env) - byte-for-byte data-equivalent to the shipped\n"
    "  file, verified by round-tripping both embedded data blobs (qf() conditions and\n"
    "  GFA_SYMPTOM_DATA_SHIPPED) back through JSON and diffing against seed_data.json /\n"
    "  symptom_data.json.\n"
    "\n"
    "  DO NOT EDIT THIS FILE. It is not wired into the app's editing workflow (the python\n"
    "  str.replace scripts that add taxa/symptoms target the real gut-flora-atlas.html, whose\n"
    "  exact minified anchor text this file's reformatting has changed). Edit\n"
    "  gut-flora-atlas.html as usual, then regenerate this file with:\n"
    "  .venv-readable/bin/python3 scripts/make_readable.py\n"
    "-->\n"
)


def find_bracket_span(text, open_idx, open_ch, close_ch):
    """Return (open_idx, close_idx) for the balanced open_ch/close_ch pair
    starting at open_idx, skipping string/template contents."""
    depth = 0
    i = open_idx
    in_str = None
    n = len(text)
    while i < n:
        c = text[i]
        if in_str:
            if c == "\\":
                i += 2
                continue
            if c == in_str:
                in_str = None
            i += 1
            continue
        if c in ("\"", "'", "`"):
            in_str = c
            i += 1
            continue
        if c == open_ch:
            depth += 1
        elif c == close_ch:
            depth -= 1
            if depth == 0:
                return open_idx, i
        i += 1
    raise ValueError("unbalanced brackets")


def verify(pretty_js):
    seed = json.load(open("seed_data.json"))["conditions"]
    sym = json.load(open("symptom_data.json"))

    m = pretty_js.find("qf = () => ({")
    if m == -1:
        m = pretty_js.find("qf=()=>({")  # in case beautifier options change
    arr_start = pretty_js.find("[", m)
    a0, a1 = find_bracket_span(pretty_js, arr_start, "[", "]")
    embedded_conditions = json.loads(pretty_js[a0 : a1 + 1])
    if embedded_conditions != seed:
        sys.exit("VERIFY FAILED: qf() conditions in beautified output don't match seed_data.json")

    m2 = pretty_js.find("GFA_SYMPTOM_DATA_SHIPPED")
    eq = pretty_js.find("=", m2)
    obj_start = pretty_js.find("{", eq)
    o0, o1 = find_bracket_span(pretty_js, obj_start, "{", "}")
    embedded_sym = json.loads(pretty_js[o0 : o1 + 1])
    if embedded_sym["symptoms"] != sym["symptoms"] or embedded_sym["bacteria"] != sym["bacteria"]:
        sys.exit("VERIFY FAILED: GFA_SYMPTOM_DATA_SHIPPED in beautified output doesn't match symptom_data.json")

    print("Verified: both embedded data blobs match their JSON sources exactly.")


def main():
    orig = open(SRC).read()
    s = orig.find("<script")
    s2 = orig.find(">", s) + 1
    e = orig.find("</script>", s2)
    js = orig[s2:e]

    opts = jsbeautifier.default_options()
    opts.indent_size = 2
    opts.max_preserve_newlines = 2
    opts.wrap_line_length = 0
    opts.brace_style = "collapse"
    pretty_js = jsbeautifier.beautify(js, opts)

    verify(pretty_js)

    new_html = orig[:s] + HEADER_COMMENT + orig[s:s2] + "\n" + pretty_js + "\n" + orig[e:]
    open(OUT, "w").write(new_html)
    print(f"Wrote {OUT} ({len(new_html):,} bytes, was {len(orig):,} bytes minified)")


if __name__ == "__main__":
    main()
