#!/usr/bin/env python3
"""Find an openly-available PDF for each cited source, at BUILD time.

The Sources tab shows a download arrow only where a free PDF actually exists.
That badge must never lie, so availability is resolved here - once, offline of
the user - rather than guessed in the browser.

WHY NOT IN THE BROWSER. It cannot work there:
  - Publisher PDFs almost never send CORS headers, so fetch() fails.
  - PMC's own /pdf/ endpoint answers a programmatic request with text/html,
    not the PDF.
So the button is a LINK, not a fetch: the browser navigates and the publisher
serves the file. No blob, no renaming, no progress bar.

WHY NOT "DOWNLOAD ALL". Fetching ~450 cross-origin PDFs is blocked by CORS,
opening 450 tabs is popup-blocked, and bulk-scraping PMC's website breaches
their access policy - they route bulk users to the OA service and FTP instead.
A local script is the right shape for that, not a web page.

HOW IT RESOLVES
  1. Every identifier already has its DOI in .citation_cache.json, which
     --verify built from NCBI's articleids. No extra lookups needed.
  2. Unpaywall (free, needs a contact email) maps DOI -> best OA PDF URL.
  3. PMC IDs fall back to the article's own /pdf/ URL, but ONLY when the
     PMC Open Access service confirms the article is in the OA subset. A
     "free to read" PMC article is not the same as a redistributable one.

Measured on this dataset: ~98% of PMIDs have a PMC record, ~90% of those are in
the OA subset. Licences are mixed (CC BY, but also NC and ND variants), which is
why nothing here downloads or republishes anything - it only links.

    python3 scripts/check_citation_coverage.py --verify   # refresh the cache
    python3 scripts/resolve_pdf_links.py --email you@example.com
"""
import argparse
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from check_citation_coverage import id_kind, load_claims  # noqa: E402

OUT = os.path.join("Porting to native react", "app", "src", "lib", "pdfLinks.js")
UNPAYWALL = "https://api.unpaywall.org/v2/"
OA_SERVICE = "https://www.ncbi.nlm.nih.gov/pmc/utils/oa/oa.fcgi?id="
UA = "GutBacteria-pdf-resolver/1.0 (https://github.com/kelcamer/GutBacteria)"

HEADER = """// GENERATED by scripts/resolve_pdf_links.py - do not edit by hand.
//
// Open-access PDF URLs, resolved at build time so the Sources tab's download
// arrow only appears where a free PDF genuinely exists. Keyed by the URL each
// source is cited under, so the component can look up what it already has.
//
// These are LINKS, not fetches - publisher PDFs do not send CORS headers, and
// PMC answers programmatic PDF requests with HTML. Nothing is downloaded or
// redistributed here; the licences are mixed (CC BY through CC BY-NC-ND).
export const PDF_LINKS = """


def get(url, pause=0.34):
    time.sleep(pause)
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8", "replace")


def unpaywall_pdf(doi, email):
    try:
        data = json.loads(get(f"{UNPAYWALL}{urllib.parse.quote(doi, safe='')}"
                              f"?email={urllib.parse.quote(email)}"))
    except (urllib.error.HTTPError, urllib.error.URLError, ValueError, TimeoutError):
        return None
    if not data.get("is_oa"):
        return None
    best = data.get("best_oa_location") or {}
    return best.get("url_for_pdf") or best.get("url")


def pmc_oa_pdf(pmcid):
    """Only offer a PMC link when the OA service confirms the OA subset."""
    try:
        xml = get(OA_SERVICE + pmcid)
    except (urllib.error.URLError, TimeoutError):
        return None
    if "<link " not in xml:
        return None
    direct = re.search(r'format="pdf"[^>]*href="([^"]+)"', xml)
    if direct:
        return direct.group(1)
    # No PDF in the package (many are tgz-only) - the article's own PDF page
    # still works in a real browser for OA articles.
    return f"https://pmc.ncbi.nlm.nih.gov/articles/{pmcid}/pdf/"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--email", required=True, help="contact email, required by Unpaywall")
    ap.add_argument("--cache", default=".citation_cache.json")
    ap.add_argument("--pdf-cache", default=".pdf_links_cache.json")
    ap.add_argument("--limit", type=int, help="resolve at most N new identifiers")
    args = ap.parse_args()

    try:
        verify_cache = json.load(open(args.cache, encoding="utf-8"))
    except (OSError, ValueError):
        print("No .citation_cache.json - run check_citation_coverage.py --verify first.",
              file=sys.stderr)
        sys.exit(1)
    try:
        pdfs = json.load(open(args.pdf_cache, encoding="utf-8"))
    except (OSError, ValueError):
        pdfs = {}

    claims, _ = load_claims("seed_data.json", "symptom_data.json")

    # Which cited URL does each identifier belong to? The tab is keyed by URL.
    url_ids = {}
    for claim in claims:
        for link_url in [t for t in claim.other_text if t and t.startswith("http")]:
            url_ids.setdefault(link_url, set()).update(claim.ids)

    todo = [i for i in sorted({i for s in url_ids.values() for i in s}) if i not in pdfs]
    if args.limit:
        todo = todo[:args.limit]
    print(f"{len(url_ids)} cited URLs, {len(todo)} identifiers still to resolve")

    for n, ident in enumerate(todo, 1):
        doi = None
        if id_kind(ident) == "DOI":
            doi = ident[4:]
        else:
            for alt in (verify_cache.get(ident) or {}).get("crosswalk", []):
                if alt.startswith("DOI:"):
                    doi = alt[4:]
                    break
        pdf = unpaywall_pdf(doi, args.email) if doi else None
        if not pdf and id_kind(ident) == "PMC":
            pdf = pmc_oa_pdf(ident)
        if not pdf:
            for alt in (verify_cache.get(ident) or {}).get("crosswalk", []):
                if alt.startswith("PMC"):
                    pdf = pmc_oa_pdf(alt)
                    break
        pdfs[ident] = pdf
        if n % 25 == 0 or n == len(todo):
            print(f"  {n}/{len(todo)} resolved")
            json.dump(pdfs, open(args.pdf_cache, "w", encoding="utf-8"), indent=1, sort_keys=True)

    json.dump(pdfs, open(args.pdf_cache, "w", encoding="utf-8"), indent=1, sort_keys=True)

    by_url = {}
    for url, ids in url_ids.items():
        for ident in sorted(ids):
            if pdfs.get(ident):
                by_url[url] = pdfs[ident]
                break

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER + json.dumps(by_url, indent=2, sort_keys=True) + "\n")
    have = sum(1 for v in pdfs.values() if v)
    print(f"{OUT}: {len(by_url)} of {len(url_ids)} cited URLs have an open PDF "
          f"({100 * len(by_url) / max(len(url_ids), 1):.0f}%)")
    print(f"identifier level: {have}/{len(pdfs)} resolved")


if __name__ == "__main__":
    main()
